### ISSUE TITLE
Wondering why this asks for github permissions?

### ISSUE THREAD

**Issue by zola-25** [axelrindle/vscode-duplicate#4]
I'm sure there's nothing malicious intended.

If it's something to do with version tracking (my git knowledge ends well before `git mv` ), can't that be done in the local repo?

Kind Regards

**Comment by axelrindle** [comment]
This is used for update checking which relies on the Github API. By signing in with Github the [API rate limit](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting) is greatly increased. [See the code here](https://github.com/axelrindle/vscode-duplicate/blob/9162e99172e5f2b7a3fcd193d70604f44f6c77cc/src/commands/version-check.ts).

I was actually thinking of whether this is actually required for a one-time call on startup.

Thanks for asking!

**Comment by zola-25** [comment]
Ah cool, yeh makes sense, like others my VS code install ends up with so many extensions it's hard to keep track of what's doing what.

Thanks for clarifying 

👍

**Comment by backermanbd** [comment]
@axelrindle On Windows, it is showing "Sign in with GitHub to use Duplicate files".
