### ISSUE TITLE
Delayed 'Extension Activation' during initial VSCode launch

### ISSUE THREAD

**Issue by backermanbd** [axelrindle/vscode-duplicate#5]
In the first scenario, when I try to duplicate a file in VSCode by right-clicking, there is a delay in extension activation, indicated by the 'activating extensions' message in the status bar.

In the second scenario, I waited for 2 minutes, but the activation delay remains. The extension activates on subsequent runs but not on the initial run.

I expect to have the extension activated before its first run rather than experiencing a delay. 

Note: I've verified the 'duplicate action' extension, which activates smoothly on VSCode startup without delay on the first run.

---
**System Information:**
 - OS: Windows 10
 - VSCode Version: 1.84
 - Extension Version: 0.1.2

**Comment by axelrindle** [comment]
@backermanbd I've updated your initial comment. Please fill out the missing details below the line.

**Comment by backermanbd** [comment]
Don't bother. I am using another one. It works as expected.

**Comment by backermanbd** [comment]
@axelrindle I have updated the information.

**Comment by backermanbd** [comment]
I've updated the extension, and it's fixed now with the latest version.
