### ISSUE TITLE
Can we add 'moving duplicate file or folder to another directory' feature?

### ISSUE THREAD

**Issue by backermanbd** [axelrindle/vscode-duplicate#7]
The title says it all.

**Comment by axelrindle** [comment]
Please add more details on what exactly you're requesting.

**Comment by backermanbd** [comment]
First, duplicate a file or folder
then simulatenously move it in another location
be it within or outside of a project

**Comment by axelrindle** [comment]
I don't see a use-case here. You can just duplicate the file/directory and move it manually to the target location.
